### ISSUE TITLE
Handle tables in step definitions

### ISSUE THREAD

**Issue by jowers** [cucumber/cucumber-ruby-tcl#10]
How can we access data bound up in tables via step definitions?

**Comment by mattwynne** [comment]
I can't honestly remember how the API will work if there's a mutli-line argument. I think we need to start with a failing feature and work our way in from there.

**Comment by jowers** [comment]
I think this one is next. I'll see if I can get something started tomorrow.

**Comment by mattwynne** [comment]
This will be trickier than #11 because you'll need to think about how to represent the table data in tcl. I'd suggest an array of arrays, but obviously I don't know much about tcl.

**Comment by mattwynne** [comment]
The code in #13 has pretty much cracked this. The one remaining puzzle is how to represent the table in tcl. I think we'll have to send it through from Ruby as an Array of Array of String (which you can get by calling `#raw` on the `DataTable` object IIRC) but you'll also need to choose the right way to represent it for tcl step authors. The Ruby step definitions get a [very rich DataTable API](http://www.rubydoc.info/github/cucumber/cucumber/Cucumber/MultilineArgument/DataTable). I'm not suggesting we implement all that now, but it's worth thinking about how we present it so we can extend it in future.

**Comment by mattwynne** [comment]
Superseded by #14
