### ISSUE TITLE
Handle DocStrings in step definitions

### ISSUE THREAD

**Issue by jowers** [cucumber/cucumber-ruby-tcl#11]
How can we handle doc strings in step definitions?

**Comment by mattwynne** [comment]
This will be easier than #10 because we can use use a String in tcl to represent the arg. We should do this one first.

**Comment by jowers** [comment]
Yup. Didn't get any time today, but might have a go over the weekend.

**Comment by mattwynne** [comment]
Fixed by 46d362cd7156b7cc4b08b4f2d742c6a93276c334
