### ISSUE TITLE
Pending Steps

### ISSUE THREAD

**Issue by jowers** [cucumber/cucumber-ruby-tcl#18]
It would be nice to have a way of marking steps as pending.

It should be easy to add a pending proc in tcl, but not sure what we'd need to do to get cucumber to display it as pending in the output?

**Comment by mattwynne** [comment]
The protocol to communicate `pending` status to cucumber is to raise an error of type [`Cucumber::Core::Test::Result::Pending`](https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/result.rb#L127) when the step is executed.

In our case, we'd need to raise that error from within the Ruby proc object constructed [here](https://github.com/cucumber/cucumber-ruby-tcl/blob/master/lib/cucumber/tcl/step_definitions.rb#L29).

We can take our pick for how to communicate from Tcl back to Ruby that this error needs to be raised. As I see it, the options are:

1. have the call to `execute_step_definition` return something special like the string `pending`
2. have the call to `execute_step_definition` raise a special Tcl error, then trap all errors and re-raise the ones recognised as pending ones as the right Ruby error.

I like option 1 better I think.

**Comment by jowers** [comment]
I assume that in option 2, you are referring to trapping of errors on the ruby side?

I think that option 1, where we raise and catch the errors on the tcl side then return an agreed string sounds best.

**Comment by mattwynne** [comment]
Can you start with a failing feature in a PR, then we can go from there?

**Comment by mattwynne** [comment]
Replaced by #22.
