### ISSUE TITLE
Add tests for failing steps / backtraces

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby-tcl#23]
As far as I can see, we've never added any tests for the behaviour when a step fails.

It would be useful to have acceptance tests for this so we can pin down the behaviour about reporting Tcl backtraces etc.

@jowers do you want to add some [characterization tests](http://en.wikipedia.org/wiki/Characterization_test) and we can see where we are?

**Comment by jowers** [comment]
Sounds sensible. I'll look at this once we've got the pending stuff done.

**Comment by jowers** [comment]
Pull request #26 created

**Comment by mattwynne** [comment]
Maybe I wasn't clear, but #26 doesn't cover what I was thinking about here.

I'm talking about the one where the step matches, runs, but throws and error, and the error messga and (Tcl) backtrace are printed to Cucumber's output.

**Comment by jowers** [comment]
Yeah, that is on the list, but I thought I'd make sure I cover all the errors. Will add a couple more over the weekend :-)

**Comment by jowers** [comment]
I've added a couple of additional tests now that demonstrate the behaviour of a failing step, and merged them back to master.
