### ISSUE TITLE
Wire protocol implementation?

### ISSUE THREAD

**Issue by d-led** [cucumber/cucumber-ruby-tcl#36]
```gherkin
Feature: Wire protocol
   In order to specify behavior of embedded Tcl software
   As a responsible developer writing stuff in Tcl
   I want to be able to drive steps defined in Tcl via the Cucumber wire protocol
```

embedded, as in Tcl interpreter hosted in a native app (or even in Ruby), where tcl*.dll is not available

## analysis

proposal, how it could work in principle: [cucumber-tcl-wire](https://github.com/d-led/cucumber-tcl-wire)

### cucumber-lua

the [lua](https://github.com/cucumber/cucumber-lua/blob/master/src/cucumber.lua) implementation seems fine for the start

**Comment by d-led** [comment]
Here's a [project](https://github.com/d-led/cucumber-tcl-wire/tree/master) demonstrating the wire protocol in principle.

@aslakhellesoy, @mattwynne : how would one go about to integrate the wire implementation into the official repo?

The reach of this library would be probably much larger, given linking to Ruby is not needed when using the wire protocol, and the potentially incompatible steps sourcing convention is not enforced.

In principle, the [wire implementation](https://github.com/d-led/cucumber-tcl-wire/blob/master/src/main/tcl/server.tcl) only references `framework.tcl`.

The [extensions to `framework.tcl`](https://github.com/d-led/cucumber-tcl-wire/blob/master/src/main/tcl/framework_extensions.tcl) are also optional, and might be submittable separately (step source location, `And` step).

The test is currently quite implicit. Is there a standard way, the wire implementations are tested?

**Comment by mattwynne** [comment]
Interesting idea!

I think I'd start by building it in a separate repo, duplicating whatever code you need from this one. Then we can have a look at whether it makes sense to combine them into one repo somehow.

It will be easier to decide when there's some real code to look at.

**Comment by d-led** [comment]
@mattwynne and code there is https://github.com/d-led/cucumber-tcl-wire

**Comment by mattwynne** [comment]
Great, OK. So is this ticket about making that repo official and bringing it under the cucumber organisation?

**Comment by d-led** [comment]
Yes, that would be great! I'd be happy if it can live and grow under the cucumber organisation, especially, synchronously with this (ruby-tcl) implementation.

**Comment by mattwynne** [comment]
@aslak_hellesoy can you take care of this, if you approve?

**Comment by d-led** [comment]
any progress on that?

**Comment by aslakhellesoy** [comment]
Hi @d-led 

Thanks for offering to bring this under the Cucumber organisation!

If you make me an admin of the project I can move it over.

**Comment by aslakhellesoy** [comment]
It's done!

**Comment by d-led** [comment]
:+1:
