### ISSUE TITLE
Reset state between scenarios

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby-tcl#4]
Do we need to implement hooks? Or create a new interpreter?

**Comment by mattwynne** [comment]
@jowers @barneyfisher if we need hooks, this is going to require some more changes to Cucumber (nothing drastic, but changes nonetheless) so it's worth you having a think about how this will work in practice so we've got a clear idea of the success criteria. Have either of you had a chance to try this out on any real code yet?

**Comment by jowers** [comment]
I think we're going to try something tomorrow/Friday on some real code to see what happens...

**Comment by mattwynne** [comment]
From what we saw in the training today, I think creating a new interpreter per test case is the right default. If we find people want to opt out of that we can look at that later.

**Comment by jowers** [comment]
Ok, we've started to get a bit of feedback on this one. The main concern so far has been being able to connect, and disconnect from the db, which I think we'd need to do by implementing hooks.

**Comment by mattwynne** [comment]
Bear in mind that as of 314caa7f232d691dc0ec9571db5e548d70fd368e we're creating a new Tcl interpreter for each scenario. I think we can close this ticket and create new ones for hooks etc.
